export const STICKERS = [
  "alia bhatt bollywood GIF by Zee Cinema Channel.gif",
  "amazon prime video mirzapur GIF.gif",
  "Angry Amazon Prime Video GIF by primevideoin.gif",
  "Angry Get Out GIF by Amazon miniTV.gif",
  "Angry Telugu Comedy GIF.gif",
  "Cutie Flirting GIF.gif",
  "Daughter Beti GIF.gif",
  "Desi GIF3.gif",
  "Desi Punjabi GIF.gif",
  "family lol GIF by The Viral Fever.gif",
  "Friends Modi GIF.gif",
  "gif.gif",
  "gif1.gif",
  "gif2.gif",
  "Girl India GIF.gif",
  "Hera Pheri GIF.gif",
  "Igmiral GIF.gif",
  "India Son GIF.gif",
  "India Trending GIF by Sonamm.gif",
  "Indian Dance GIF.gif",
  "Indian Desi GIF.gif",
  "Indian Desi GIF1.gif",
  "Making Tea GIF.gif",
  "Modi Bjp GIF by Indian National Congress.gif",
  "Modiji GIF.gif",
  "Mood You Cant GIF by primevideoin.gif",
  "Narendra Modi GIF.gif",
  "Nawazuddin Siddiqui Bollywood GIF by Eros Now.gif",
  "Next Level Interview GIF.gif",
  "Plead Amazon Prime Video GIF by primevideoin.gif",
  "Pm Modi GIF.gif",
  "Rahul Gandhi India GIF.gif",
  "ranveer singh bollywood GIF by Zee Cinema Channel.gif",
  "Salman Khan Cat GIF.gif",
  "Salman Khan GIF by HackerMarathi.IN.gif",
  "shah rukh khan bollywood GIF.gif",
  "Son Beta GIF.gif",
  "Son Desi GIF1.gif",
  "Sorry Rahul Gandhi GIF.gif",
  "Varun Dhawan Sara GIF by Pooja Entertainment.gif"
];

export const STICKER_DURATIONS = {
  "alia bhatt bollywood GIF by Zee Cinema Channel.gif": 5600,
  "amazon prime video mirzapur GIF.gif": 1480,
  "Angry Amazon Prime Video GIF by primevideoin.gif": 2160,
  "Angry Get Out GIF by Amazon miniTV.gif": 1740,
  "Angry Telugu Comedy GIF.gif": 6470,
  "Cutie Flirting GIF.gif": 1600,
  "Daughter Beti GIF.gif": 2870,
  "Desi GIF3.gif": 403280,
  "Desi Punjabi GIF.gif": 2870,
  "family lol GIF by The Viral Fever.gif": 1540,
  "Friends Modi GIF.gif": 2670,
  "gif.gif": 4270,
  "gif1.gif": 1270,
  "gif2.gif": 391440,
  "Girl India GIF.gif": 2870,
  "Hera Pheri GIF.gif": 2990,
  "Igmiral GIF.gif": 3000,
  "India Son GIF.gif": 2870,
  "India Trending GIF by Sonamm.gif": 2250,
  "Indian Dance GIF.gif": 4400,
  "Indian Desi GIF.gif": 1190,
  "Indian Desi GIF1.gif": 2870,
  "Making Tea GIF.gif": 6500,
  "Modi Bjp GIF by Indian National Congress.gif": 140,
  "Modiji GIF.gif": 1590,
  "Mood You Cant GIF by primevideoin.gif": 2560,
  "Narendra Modi GIF.gif": 2270,
  "Nawazuddin Siddiqui Bollywood GIF by Eros Now.gif": 603590,
  "Next Level Interview GIF.gif": 1880,
  "Plead Amazon Prime Video GIF by primevideoin.gif": 1960,
  "Pm Modi GIF.gif": 6470,
  "Rahul Gandhi India GIF.gif": 6470,
  "ranveer singh bollywood GIF by Zee Cinema Channel.gif": 4200,
  "Salman Khan Cat GIF.gif": 2870,
  "Salman Khan GIF by HackerMarathi.IN.gif": 1940,
  "shah rukh khan bollywood GIF.gif": 4830,
  "Son Beta GIF.gif": 2870,
  "Son Desi GIF1.gif": 2870,
  "Sorry Rahul Gandhi GIF.gif": 5140,
  "Varun Dhawan Sara GIF by Pooja Entertainment.gif": 800
};